### ISSUE TITLE
Why is num_steps_postierior always 0?

### ISSUE THREAD

**Issue by janbolle** [katerakelly/oyster#26]
Dear @katerakelly, @azhou42,

I was wondering why in the default (and all other configs) `num_steps_posterior=0`.
Wouldn't it be good to train our encoder using prior knowledge?

**Comment by katerakelly** [comment]
Hi, sorry for the late reply!

We use `num_steps_posterior>0` in the sparse reward pointmass experiment, see the config here: https://github.com/katerakelly/oyster/blob/44e20fddf181d8ca3852bdf9b6927d6b8c6f48fc/configs/sparse-point-robot.json

We treated this as a hyperparameter and found that for the dense reward MuJoCo tasks, `0` worked fine. The reason is likely that those tasks don't require coordinated exploration to collect context that has task information. The sparse-reward pointmass task does require coherent exploration, and performing multiple iterations of posterior sampling facilitates that.
